export const GET_GRAPH_DATA = 'GET_GRAPH_DATA';
export const GET_GRAPH_DATA_SUCCESS = 'GET_GRAPH_DATA_SUCCESS';
export const GET_GRAPH_DATA_ERROR = 'GET_GRAPH_DATA_ERROR';

export const GET_ANALYTICS_DETAILS = 'GET_ANALYTICS_DETAILS';
export const GET_ANALYTICS_DETAILS_SUCCESS = 'GET_ANALYTICS_DETAILS_SUCCESS';
export const GET_ANALYTICS_DETAILS_ERROR = 'GET_ANALYTICS_DETAILS_ERROR';