# Generated by Django 2.2.5 on 2019-09-22 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0003_mailinglist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mailinglist',
            name='status',
            field=models.CharField(choices=[('N', 'Unprocessed'), ('S', 'Subscribed'), ('U', 'Unsubscribed')], default='N', max_length=1),
        ),
    ]
