# Generated by Django 2.2.5 on 2019-09-23 03:35

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0004_auto_20190922_0811'),
    ]

    operations = [
        migrations.AddField(
            model_name='mailinglist',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='mailinglist',
            name='status',
            field=models.CharField(choices=[('N', 'Unprocessed'), ('S', 'Subscribed'), ('U', 'Unsubscribed')], default='N', max_length=1),
        ),
    ]
