# Generated by Django 2.2.2 on 2019-06-11 03:03

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.db.models.functions.text
import re


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('slug', models.SlugField()),
            ],
            options={
                'verbose_name_plural': 'Categories',
                'ordering': (django.db.models.functions.text.Lower('name'),),
            },
        ),
        migrations.CreateModel(
            name='Narration',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('S', 'Assigned'), ('Y', 'Accepted'), ('N', 'Rejected'), ('R', 'Review'), ('M', 'Modification Required'), ('L', 'Approved')], db_index=True, default='S', max_length=1)),
                ('public', models.BooleanField(db_index=True, default=False)),
                ('url', models.URLField()),
                ('title', models.CharField(db_index=True, max_length=500, null=True)),
                ('slug', models.SlugField(max_length=2000, null=True, validators=[django.core.validators.RegexValidator(re.compile('^[-a-zA-Z0-9_]+\\Z'), "Enter a valid 'slug' consisting of letters, numbers, underscores or hyphens.", 'invalid')])),
                ('description', models.TextField(null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True, null=True)),
                ('publish_date', models.DateTimeField(blank=True, null=True)),
                ('expiry_date', models.DateTimeField(blank=True, null=True)),
                ('content', models.TextField(null=True)),
                ('narrator_notes', models.TextField(blank=True, null=True)),
                ('audio_length', models.DurationField(blank=True, null=True)),
                ('audio_hub', models.BooleanField(default=True)),
                ('library', models.BooleanField(default=True)),
                ('podcast', models.BooleanField(default=True)),
                ('podcast_description', models.TextField(blank=True, null=True)),
                ('episode_notes', models.TextField(blank=True, null=True)),
                ('featured_image', models.ImageField(blank=True, null=True, upload_to='narration/featured_image/', verbose_name='Featured Image')),
                ('customer_notes', models.TextField(blank=True, null=True)),
                ('word_count', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Narrator',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=60)),
                ('last_name', models.CharField(max_length=60)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=1)),
                ('sample_url', models.URLField()),
                ('enabled', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ('first_name', 'last_name'),
            },
        ),
        migrations.CreateModel(
            name='NarratorLanguage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Playlist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('created_dt', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ('-created_dt',),
            },
        ),
        migrations.CreateModel(
            name='PlaylistNarrationsThroughModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(db_index=True, editable=False, verbose_name='order')),
                ('narration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='narrations_data', to='narrations.Narration')),
                ('playlist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='narrations_data', to='narrations.Playlist')),
            ],
            options={
                'ordering': ('order',),
            },
        ),
    ]
