# Generated by Django 2.2.2 on 2019-06-11 03:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
        ('narrations', '0001_initial'),
        ('uploader', '0001_initial'),
        ('sales', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='playlist',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='users.Customer'),
        ),
        migrations.AddField(
            model_name='playlist',
            name='narrations',
            field=models.ManyToManyField(through='narrations.PlaylistNarrationsThroughModel', to='narrations.Narration'),
        ),
        migrations.AddField(
            model_name='narrator',
            name='languages',
            field=models.ManyToManyField(blank=True, related_name='narrators', to='narrations.NarratorLanguage'),
        ),
        migrations.AddField(
            model_name='narration',
            name='audio_file',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='uploader.FileItem'),
        ),
        migrations.AddField(
            model_name='narration',
            name='categories',
            field=models.ManyToManyField(to='narrations.Category'),
        ),
        migrations.AddField(
            model_name='narration',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='users.Customer'),
        ),
        migrations.AddField(
            model_name='narration',
            name='narrator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='narrations.Narrator'),
        ),
        migrations.AddField(
            model_name='narration',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='narrations', to='sales.Order'),
        ),
        migrations.AddField(
            model_name='category',
            name='parent',
            field=models.ManyToManyField(blank=True, to='narrations.Category'),
        ),
        migrations.AlterUniqueTogether(
            name='narration',
            unique_together={('customer', 'slug')},
        ),
    ]
