# Generated by Django 2.2.2 on 2019-06-15 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('narrations', '0002_auto_20190611_0303'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='narration',
            name='audio_length',
        ),
        migrations.RemoveField(
            model_name='narration',
            name='episode_notes',
        ),
        migrations.RemoveField(
            model_name='narration',
            name='podcast_description',
        ),
        migrations.RemoveField(
            model_name='narration',
            name='public',
        ),
        migrations.AddField(
            model_name='narration',
            name='featured_library',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='narration',
            name='audio_hub',
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AlterField(
            model_name='narration',
            name='content',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='narration',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='narration',
            name='library',
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AlterField(
            model_name='narration',
            name='podcast',
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AlterField(
            model_name='narration',
            name='word_count',
            field=models.PositiveIntegerField(blank=True),
        ),
    ]
