# Generated by Django 2.2.2 on 2019-06-15 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('narrations', '0003_auto_20190615_1954'),
    ]

    operations = [
        migrations.AddField(
            model_name='narration',
            name='audio_length',
            field=models.DurationField(blank=True, null=True),
        ),
    ]
