# Generated by Django 2.2.3 on 2019-07-31 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('narrations', '0004_narration_audio_length'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='narration',
            options={'ordering': ['id']},
        ),
        migrations.RemoveField(
            model_name='narration',
            name='audio_length',
        ),
        migrations.AlterField(
            model_name='narration',
            name='featured_image',
            field=models.ImageField(blank=True, max_length=255, null=True, upload_to='narration/featured_image/', verbose_name='Featured Image'),
        ),
    ]
