# Generated by Django 2.2.3 on 2019-08-08 00:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('narrations', '0005_auto_20190731_0458'),
    ]

    operations = [
        migrations.AddField(
            model_name='playlist',
            name='playlist_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
