# Generated by Django 2.2.4 on 2019-08-21 19:05

import apps.narrations.models
import django.contrib.postgres.indexes
import django.contrib.postgres.search
from django.db import migrations, models
from django.contrib.postgres.operations import BtreeGistExtension
from django.contrib.postgres.operations import TrigramExtension


class Migration(migrations.Migration):

    dependencies = [
        ('narrations', '0006_playlist_playlist_url'),
    ]

    operations = [
        BtreeGistExtension(),
        TrigramExtension(),
        migrations.AlterModelOptions(
            name='narration',
            options={'ordering': ['-id']},
        ),
        migrations.AddField(
            model_name='narration',
            name='search_vector',
            field=django.contrib.postgres.search.SearchVectorField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='narration',
            name='featured_image',
            field=models.ImageField(blank=True, max_length=255, null=True, upload_to=apps.narrations.models.customer_image_path, verbose_name='Featured Image'),
        ),
        migrations.AddIndex(
            model_name='narration',
            index=django.contrib.postgres.indexes.GinIndex(fields=['search_vector'], name='title_index'),
        ),
    ]
