# Generated by Django 2.2.4 on 2019-08-13 01:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0003_customer_audio_hub_description'),
        ('uploader', '0003_fileitem_audio_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='PodcastCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('feed_output', models.CharField(max_length=100)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='parents', to='podcasts.PodcastCategory')),
            ],
        ),
        migrations.CreateModel(
            name='PodcastFeed',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feed_slug', models.CharField(max_length=120)),
                ('title', models.CharField(max_length=120)),
                ('description', models.CharField(blank=True, max_length=500, null=True)),
                ('image', models.ImageField(upload_to='')),
                ('category_detailed', models.ForeignKey(limit_choices_to={'parent': True}, on_delete=django.db.models.deletion.DO_NOTHING, related_name='detailed_category', to='podcasts.PodcastCategory')),
                ('category_top', models.ForeignKey(limit_choices_to={'parent': None}, on_delete=django.db.models.deletion.DO_NOTHING, related_name='top_category', to='podcasts.PodcastCategory')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='users.Customer')),
            ],
        ),
        migrations.CreateModel(
            name='PodcastEpisode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('description', models.CharField(blank=True, max_length=500, null=True)),
                ('episode_notes', models.CharField(blank=True, max_length=500, null=True)),
                ('link', models.URLField(blank=True, null=True)),
                ('publish_date', models.DateTimeField(blank=True, null=True)),
                ('audio_file', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='uploader.FileItem')),
                ('feed', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='podcasts.PodcastFeed')),
            ],
        ),
    ]
