# Generated by Django 2.2.2 on 2019-06-11 03:03

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('publish_date', models.DateField(auto_now_add=True)),
                ('status', models.CharField(choices=[('D', 'Draft'), ('P', 'Published')], db_index=True, default='D', max_length=1)),
                ('slug', models.SlugField(max_length=255)),
                ('title', models.CharField(max_length=128)),
                ('image', models.ImageField(upload_to='')),
                ('description', models.TextField()),
                ('player_username', models.CharField(blank=True, max_length=64, null=True)),
                ('player_narration', models.CharField(blank=True, max_length=30, null=True, validators=[django.core.validators.validate_integer])),
                ('content', models.TextField(blank=True)),
                ('notes', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
