# Generated by Django 2.2.3 on 2019-07-31 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='compact_player',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='customer',
            name='enterprise',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='customer',
            name='google_analytics',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
