# Generated by Django 2.2.4 on 2019-08-12 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20190731_0458'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='audio_hub_description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
