# Generated by Django 2.2.4 on 2019-08-21 19:05

import django.core.validators
from django.db import migrations, models
import re


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_customer_audio_hub_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='short_name',
            field=models.CharField(db_index=True, max_length=60, null=True, validators=[django.core.validators.RegexValidator(re.compile('^[-a-zA-Z0-9_]+\\Z'), "Enter a valid 'slug' consisting of letters, numbers, underscores or hyphens.", 'invalid')]),
        ),
    ]
