# Generated by Django 2.2.2 on 2019-06-15 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uploader', '0002_auto_20190611_0303'),
    ]

    operations = [
        migrations.AddField(
            model_name='fileitem',
            name='audio_length',
            field=models.DurationField(blank=True, null=True),
        ),
    ]
